### ISSUE TITLE
Song title doesn't get extracted correctly

### ISSUE THREAD

**Issue by dbrunek** [onnowhere/youtube_music_playlist_downloader#13]
The title in the metadata of the generated mp3 seems to always be the full song the name of the YouTube video whether use_title is set to true or false.

I know this is only a small project for educational purpose, but i would really appreciate if you could take a look at it.

The overall problem seems to be an HTTP error 400: Bad request when trying to download the API page. So there is no metadata at all except for the artist name.

**Comment by onnowhere** [comment]
It looks like there was an update to YT API and yt-dlp needs an update. I will update the release in a bit.

**Comment by onnowhere** [comment]
Issue should now be fixed in latest release. Thanks for reporting this! Let me know if there's further issues.
https://github.com/onnowhere/youtube_music_playlist_downloader/releases
