### ISSUE TITLE
doesn't work anymore

### ISSUE THREAD

**Issue by vegasxvince** [onnowhere/youtube_music_playlist_downloader#14]
I've used it before and it worked so i know i have ffmpeg correctly installed, but when I redownloaded ympd now it says:
**"WARNING: Youtube said: ERROR - precondition check failed.
HTTP ERROR 400: Bad request.
Unable to download API page"**
and only downloads the thumbnail of the first song.

**Comment by onnowhere** [comment]
Issue should now be fixed in latest release. Thanks for reporting this! Let me know if there's further issues.
https://github.com/onnowhere/youtube_music_playlist_downloader/releases
