### ISSUE TITLE
Fresh install won't run

### ISSUE THREAD

**Issue by paulcanning** [onnowhere/youtube_music_playlist_downloader#8]
Using Python 3.8.2, installed requirements using pip3, ran `python3 youtube_music_playlist_downloader.py` and I get the following error

```
Traceback (most recent call last):
  File "youtube_music_playlist_downloader.py", line 9, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by onnowhere** [comment]
Sorry just saw this, try running `pip install requests`? I may have left this out of requirements by accident or something

**Comment by onnowhere** [comment]
Closing from no response
