### ISSUE TITLE
Only one Artists instead of all contributing

### ISSUE THREAD

**Issue by ShadicSlash** [onnowhere/youtube_music_playlist_downloader#9]
I don't know how to make requests so here I am again in "Issues".

In metadata, some songs have "other artists" and they all show up as a big artist name and it screws up my library.
It would be better if the main artist was the "album artist" and the rest in "contributing".

Please add the album tracknumbering in metadata

Also the Album year is often not correct as shown in my second picture. It seems like it's the year it was added to youtube music instead than the Album's.

Thank you for your hard work again.

Here is a picture of an example:
![image](https://github.com/onnowhere/youtube_music_playlist_downloader/assets/125931844/2d1c051f-0722-47ba-bebf-baae5401e0e3)

![image](https://github.com/onnowhere/youtube_music_playlist_downloader/assets/125931844/356a6892-0ca9-499f-a9a4-39abd1ef3e4c)

**Comment by onnowhere** [comment]
This seems to be some sort of YouTube Music specific feature that may or may not be accessible from ytdlp at the moment (albums/main artist/album release year)... The year should be based on the upload date so also curious why the song would give 2017. Will have to investigate

**Comment by onnowhere** [comment]
@ShadicSlash is this resolved?

**Comment by ShadicSlash** [comment]
There's not really much to do like you said for most because it's on Youtube side. So I guess it's resolved.
